package com.control;

public enum QuestionType {
	CARE_ABOUT_GODS_EXISTENCE,
	NUMBER_OF_GODS_TO_BELIEVE, 
	HUMAN_FORM_OF_GOD,
	CARE_ABOUT_HELL_EXISTENCE,
	CARE_ABOUT_HEAVEN_EXISTENCE,
	BELIEF_IN_REINCARNATION,
	NESSESITY_OF_PRAYER,
	NESSESITY_OF_MEDITATION,
	ACCEPTANCE_LEVEL_OF_HOMOSEXUALITY,
	ACCEPTANCE_LEVEL_OF_ABORTION,
	ACCEPTANCE_LEVEL_OF_EUTHANASIA,
	RESTRICTIONS_OF_SEXUALITY,
	VIEW_OF_POLYGAMY,
	
	MANIFESTATION_IN_DOCTRINAL_DIMENSION,
	MANIFESTATION_BY_RITUALS,
	SOCIAL_ORGANISATIONAL_SIDE,
	INDIVIDUAL_SPIRITUALITY,
	
	NUMBER_OF_FOLLOWERS,
	TIME_OF_EXISTANCE,
	PROCEEDINGS_WITH_DEAD,
	
	OBLIGATION_OF_PRAYER,
	PROHIBITION_FOR_ALCOHOL,
	PROHIBITION_FOR_PORK,
	NEED_OF_PILGRIMAGE,
	LACTOVEGETARIAN_DIET,
	PROHIBITION_FOR_BEEF,
	CIRCUMCISION,
	FAST,
	KOSHER,
	HOME_ALTAR,
	NECESSITY_OF_GIFT,
	ANTHROPOMORPHIC_GODS,
	FRUITARIAN_DIET,
	
	FOO,
	BAR,
	FIZZ,
	BUZZ
}
