package com.control;

public enum QuestionType {
	CARE_ABOUT_GODS_EXISTENCE,
	NUMBER_OF_GODS_TO_BELIEVE, 
	HUMAN_FORM_OF_GOD,
	CARE_ABOUT_HELL_EXISTENCE,
	CARE_ABOUT_HEAVEN_EXISTENCE,
	BELIEF_IN_REINCARNATION,
	NESSESITY_OF_PRAYER,
	NESSESITY_OF_MEDITATION,
	ACCEPTANCE_LEVEL_OF_HOMOSEXUALITY,
	ACCEPTANCE_LEVEL_OF_ABORTION,
	ACCEPTANCE_LEVEL_OF_EUTHANASIA,
	RESTRICTIONS_OF_SEXUALITY,
	VIEW_OF_POLYGAMY
}
